telegram:
  bot:
    webhook: https://e25f-89-106-170-30.eu.ngrok.io
    name: "@petPRJbot"
    token: 5527146485:AAGtRZMNo2_U9YKEPXmM6loB3z2gHV5c-tw
spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    hikari:
      username: java
      password: pass
      jdbc-url: jdbc:postgresql://localhost:5432/reminder
    url: jdbc:postgresql://localhost:5432/reminder

#  server:
#    port: 8080

#  https://api.telegram.org/bot5527146485:AAGtRZMNo2_U9YKEPXmM6loB3z2gHV5c-tw/setWebhook?url=<URL, полученный от ngrok>