telegram:
  bot:
    webhook: https://1615-109-252-70-57.eu.ngrok.io
    name: "@petPRJbot"
    token: 5527146485:AAGtRZMNo2_U9YKEPXmM6loB3z2gHV5c-tw
spring:
#  datasource:
#    hikari:
#      username: java
#      password: pass
#      jdbc-url: jdbc:postgresql://localhost:5432/reminder
#    url: jdbc:postgresql://localhost:5432/reminder
  datasource:
    hikari:
      username: nlynipmseatzsm
      password: fed3d46587fb2a0f865a3a1f3ca26ee8e9976e25aa28c3c46ffca55202d6ba2a
#      jdbc-url: postgres://nlynipmseatzsm:fed3d46587fb2a0f865a3a1f3ca26ee8e9976e25aa28c3c46ffca55202d6ba2a@ec2-34-249-161-200.eu-west-1.compute.amazonaws.com:5432/d9cioqhsevoagg
    url: postgres://nlynipmseatzsm:fed3d46587fb2a0f865a3a1f3ca26ee8e9976e25aa28c3c46ffca55202d6ba2a@ec2-34-249-161-200.eu-west-1.compute.amazonaws.com:5432/d9cioqhsevoagg

#  https://api.telegram.org/bot5527146485:AAGtRZMNo2_U9YKEPXmM6loB3z2gHV5c-tw/setWebhook?url=<URL, полученный от ngrok>